import type { Metadata } from "next";
import { geistSans, geistMono, inter, red_rose, instrument_sans } from "@/lib/font";
import "@/globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${instrument_sans.variable} ${inter.variable} ${red_rose.variable} antialiased h-screen w-full overflow-x-hidden`}
      >
        {children}
      </body>
    </html>
  );
}
